<a href="https://colab.research.google.com/github/mzignis/tensorflow_2.0_tutorial/blob/master/01_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Flow 2.0 - Basic

In [0]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0-rc2'

## Constants

In [3]:
tensor_const = tf.constant([[32, 4], [12, 43]])
tensor_const

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32,  4],
       [12, 43]], dtype=int32)>

In [4]:
tensor_const.shape

TensorShape([2, 2])

In [5]:
tensor_const.numpy()

array([[32,  4],
       [12, 43]], dtype=int32)

In [6]:
np_tensor = np.array([[1, 2], [3, 4]])
tensor_const = tf.constant(np_tensor)
tensor_const

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

## Variables

In [7]:
tensor_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tensor_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [8]:
tensor_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
tensor_variable[0, 2].assign(100)
tensor_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## Operations

In [11]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [13]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [14]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [16]:
np.dot(tensor, tensor_const)

array([[ 7, 10],
       [15, 22]])

## Strings

In [17]:
tensor_string = tf.constant('Tensor Flow 2.0')
tensor_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensor Flow 2.0'>

In [19]:
tf.strings.length(tensor_string)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [20]:
tf.strings.unicode_decode(tensor_string, 'UTF-8')

<tf.Tensor: shape=(15,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114,  32,  70, 108, 111, 119,  32,  50,
        46,  48], dtype=int32)>

In [21]:
tensor_string_array = tf.constant(['Tensor', 'Flow', '2.0'])
tensor_string_array

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Tensor', b'Flow', b'2.0'], dtype=object)>

In [22]:
for tf_string in tensor_string_array:
    print(tf_string)

tf.Tensor(b'Tensor', shape=(), dtype=string)
tf.Tensor(b'Flow', shape=(), dtype=string)
tf.Tensor(b'2.0', shape=(), dtype=string)
